import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import SessionProviderComp from '@/components/nextauth/SessionProvider'
import { CartProvider } from '@/cart/CartContext'
import { Toaster } from 'react-hot-toast';
import StoreProvider from './StoreProvider';

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Stylish - Clothes Paradise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode
  session: any
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#07be8a" />
        <SessionProviderComp session={session}>
          <StoreProvider>
            <ThemeProvider
              attribute='class'
              enableSystem={true}
              defaultTheme='light'>
              
              <Toaster
                position="top-center"
                reverseOrder={false}
                toastOptions={{
                  className: 'items-start w-auto max-w-lg', 
                  
                  style: {
                    borderRadius: '8px',
                    background: '#333',
                    color: '#fff',
                  },
                  success: {
                    iconTheme: {
                      primary: '#10B981',
                      secondary: '#fff',
                    },
                    style: {
                      background: '#F0FDF4',
                      color: '#14532D',
                      border: '1px solid #D1FAE5',
                    },
                  },
                  error: {
                    iconTheme: {
                      primary: '#EF4444',
                      secondary: '#fff',
                    },
                    style: {
                      background: '#FEF2F2',
                      color: '#991B1B',
                      border: '1px solid #FECACA',
                    },
                  },
                }}
              />

              <Header />
              {children}
              <Footer />
            </ThemeProvider>
          </StoreProvider> 
        </SessionProviderComp>
      </body>
    </html>
  )
}